"""Training-step model: forward + backward + optimizer.

A linear layer  Y = X @ W   with  X: (M, K),  W: (K, N),  Y: (M, N)
has three GEMMs per training step:

  forward  : Y      = X   @ W        -> (M, K) x (K, N)
  dgrad    : dX     = dY  @ W^T       -> (M, N) x (N, K)   (input gradient)
  wgrad    : dW     = X^T @ dY        -> (K, M) x (M, N)   (weight gradient)

So the backward pass is ~2x the forward MACs (two GEMMs of the same total
work), matching the standard rule of thumb.

DRAM traffic per GEMM comes from `simulator.memory.gemm_traffic`
(compulsory + tiling penalty, dataflow-independent).  A Timeloop cross-check
(see docs/dataflow_choice.md) showed the dataflow choice does *not* change
DRAM traffic for a well-scheduled GEMM -- an earlier "output-stationary wgrad
wins" result was a modelling artifact and has been retracted.

`recompute` (activation checkpointing, `training_step`/`model_step` keyword):
the input activation is regenerated by re-running the forward GEMM in the
backward pass instead of being read from DRAM -- trading traffic for compute.
A win only while the layer is memory-bound; dead weight once compute-bound.
See docs/recomputation.md. Silicon-anchored: `validate/silicon/profile_recompute.py`.

Optimizer state (Adam)
----------------------
Per parameter, fp32 training keeps: param, grad, first moment (m), second
moment (v). Momentum + variance roughly *double* the resident parameter
memory relative to params alone. The update is pure bandwidth.

`Optimizer` exposes two levers: the precision of m, v (`state_bytes`:
4 fp32 / 2 bf16 / 1 fp8) and whether they stay resident in SRAM
(`state_resident`) instead of spilling to DRAM.

Removed (2026-09): a `BackwardReuse` lever (on-chip reuse across dgrad/wgrad)
and a GEMM-operand `Precision` lever (fp8 compute) both existed here but were
untestable on the hardware available to validate this project -- the first
has no GPU-exposed control to toggle for real, the second needs Hopper/Ada+
tensor cores this project's silicon anchor (a Tesla T4) doesn't have. Cut
rather than kept as unvalidatable claims; see git history if reviving either
becomes possible.
"""

from dataclasses import dataclass
import dataclasses
import math

from .attention import Attention, attention_step
from .compute import Hardware, matmul_seconds, elementwise_seconds, _occupancy
from .memory import Memory, gemm_traffic


MASTER_BYTES_PER_PARAM = 4  # fp32 master weight + gradient
_CHECKPOINT_FRACTION = 0.4  # sqrt-checkpointing keeps ~1/sqrt(6) of activations
                            # for a 6-layer block (Chen et al. 2016)

# A real Adam step is a chain of small per-tensor elementwise kernels
# (mul, addcmul, pow, div, copy ...), not one bandwidth stream.  On tiny
# layers it is launch-latency-bound.  `_ADAM_KERNEL_LAUNCHES * launch_s`
# is added as a floor; launch_s = 0 keeps the abstract model unchanged.
_ADAM_KERNEL_LAUNCHES = 12


@dataclass(frozen=True)
class Optimizer:
    """Adam optimizer-state + update-streaming config.

    Per parameter the update touches: the master weight (fp32), the gradient
    dW (just produced by wgrad, so it stays on chip -- free), and the two
    running averages m, v at `state_bytes` precision.

    * state_bytes    -- 4 fp32 / 2 bf16 / 1 fp8.  Halving it halves the m,v
                        DRAM stream, which is the bulk of the optimizer cost.
    * state_resident -- keep m, v in SRAM across the step instead of spilling
                        them to DRAM.  Only possible when they fit.
    """

    state_bytes: int = 4
    state_resident: bool = False


ADAM_FP32 = Optimizer(state_bytes=4)
ADAM_BF16_STATE = Optimizer(state_bytes=2)
ADAM_FP8_STATE = Optimizer(state_bytes=1)


@dataclass(frozen=True)
class Layer:
    name: str
    M: int   # batch * sequence  (tokens)
    K: int   # input features
    N: int   # output features

    @property
    def param_count(self) -> int:
        return self.K * self.N


@dataclass(frozen=True)
class StepBreakdown:
    layer: str
    forward_s: float
    backward_s: float
    optimizer_s: float
    forward_bound: str
    backward_bound: str
    backward_bytes: float = 0.0
    activation_bytes: float = 0.0   # stored activations, per microbatch (peak)

    @property
    def total_s(self) -> float:
        return self.forward_s + self.backward_s + self.optimizer_s

    @property
    def bottleneck(self) -> str:
        """Which bound dominates the compute-heavy fwd+bwd portion."""
        return self.backward_bound  # backward is the larger phase


def _phase_seconds(M, N, K, hw: Hardware, mem: Memory):
    """max(compute, memory) for one GEMM, plus which bound wins."""
    compute_s = matmul_seconds(M, N, K, hw)
    memory_s = gemm_traffic(M, N, K, hw, mem).total_bytes / mem.achievable_bw
    bound = "compute" if compute_s >= memory_s else "memory"
    return max(compute_s, memory_s), bound


def _backward_seconds(layer: Layer, hw: Hardware, mem: Memory, recompute: bool = False):
    """dgrad + wgrad as two GEMMs, each max(compute, DRAM traffic).

        dgrad  dX = dY @ W^T   GEMM (M=tok,      N=in_feat,  K=out_feat)
        wgrad  dW = X^T @ dY   GEMM (M=in_feat,  N=out_feat, K=tok)

    Traffic per GEMM comes from `gemm_traffic` (compulsory + tiling penalty,
    dataflow-independent -- validated). `recompute` -- X is regenerated (one
    forward GEMM) rather than read by wgrad.
    """
    M, K, N = layer.M, layer.K, layer.N   # tokens, in-features, out-features
    xa = M * K * hw.mac_bytes             # input activation X (== dX, the dgrad output)

    def bwd_matmul(m_, n_, k_):
        """One backward GEMM (dgrad or wgrad). `backward_util_tiles`
        relieves an occupancy PENALTY for a skinny output when set.

        TRIED AND REVERTED: an `occupancy_safe_backward_efficiency` boost
        for GEMMs whose output is already occupancy-safe, calibrated
        against a GEMM-size sweep (docs/silicon_anchor.md) where the
        implied efficiency looked like a clean ce~1.0 plateau. It did
        nothing for the very cases it was fit on: those GEMMs are
        MEMORY-bound under `_backward_seconds`'s `max(compute, memory)`
        (their weight matrix exceeds this GPU's L2, triggering the
        traffic-penalty branch), so adjusting compute_efficiency is
        invisible to the final max()'d result. Checking the arithmetic
        confirmed it: matching the measured time as a memory-bound
        quantity would need ~451 GB/s on a GPU with a 320 GB/s physical
        maximum -- impossible. The real gap is in `gemm_traffic`'s
        penalty-term heuristic (already documented as unvalidated), not
        compute_efficiency. Not adopted.
        """
        eff_hw = hw
        if hw.backward_util_tiles is not None and _occupancy(m_, n_, hw) < 0.999:
            eff_hw = dataclasses.replace(hw, util_tiles=hw.backward_util_tiles)
        return matmul_seconds(m_, n_, k_, eff_hw)

    compute_s = bwd_matmul(M, K, N)      # dgrad
    compute_s += bwd_matmul(K, N, M)     # wgrad
    if recompute:
        compute_s += matmul_seconds(M, N, K, hw)      # regenerate X -- this IS the
                                                       # forward GEMM, forward's efficiency

    dgrad_bytes = gemm_traffic(M, K, N, hw, mem).total_bytes
    wgrad_bytes = gemm_traffic(K, N, M, hw, mem).total_bytes
    if recompute:
        wgrad_bytes -= xa               # X regenerated on chip, not read

    bytes_moved = max(0.0, dgrad_bytes) + max(0.0, wgrad_bytes)
    memory_s = bytes_moved / mem.achievable_bw
    bound = "compute" if compute_s >= memory_s else "memory"
    return max(compute_s, memory_s), bound, bytes_moved


def optimizer_seconds(layer: Layer, mem: Memory,
                      opt: Optimizer = ADAM_FP32,
                      hw: Hardware | None = None) -> float:
    """Adam update cost: DRAM traffic + elementwise compute + a small-layer
    kernel-launch floor.

    Always streamed: master weight read + write (fp32).  The gradient dW is
    produced by wgrad and consumed on chip -- free.  m and v are streamed
    (read + write) unless they are held resident and fit in SRAM.

    Real Adam is a chain of ~12 per-tensor elementwise kernels, so on tiny
    layers it is launch-latency-bound; `hw.kernel_launch_s` (0 for the
    abstract model) adds that floor. The elementwise arithmetic itself
    (mul/addcmul/sqrt/div) also costs real compute, priced by
    `elementwise_seconds` (0 for the abstract model). When `opt.state_bytes`
    isn't in `hw.native_low_precision_bytes` (e.g. bf16 state on a Turing/
    Volta GPU with no native bf16 ALU throughput), that compute is emulated
    at `hw.emulation_penalty`x -- which can outweigh the smaller byte count
    a lower-precision state would otherwise save. See docs/optimizer_state.md.
    """
    n = layer.param_count
    bytes_moved = 2 * n * MASTER_BYTES_PER_PARAM          # master weight r+w
    mv = 2 * n * opt.state_bytes                          # m + v
    if not (opt.state_resident and mv <= mem.sram_bytes):
        bytes_moved += 2 * mv                             # m,v read + write
    launch_s = _ADAM_KERNEL_LAUNCHES * hw.kernel_launch_s if hw else 0.0
    elem_s = 0.0
    if hw is not None:
        native = opt.state_bytes in hw.native_low_precision_bytes
        elem_s = elementwise_seconds(n, hw, native=native)
    return bytes_moved / mem.achievable_bw + launch_s + elem_s


def optimizer_state_bytes(layer: Layer, opt: Optimizer = ADAM_FP32) -> int:
    """Resident footprint added by Adam: m + v."""
    return 2 * layer.param_count * opt.state_bytes


def training_step(layer: Layer, hw: Hardware, mem: Memory,
                  opt: Optimizer = ADAM_FP32, *,
                  recompute: bool = False,
                  microbatch: int | None = None) -> StepBreakdown:
    """One optimizer step over `layer.M` tokens.

    `microbatch` (gradient accumulation): process the M tokens in
    ceil(M / microbatch) chunks, accumulating dW, and run the optimizer once.
    Trades K x the per-GEMM fixed overhead + K x the weight re-reads + smaller
    (lower-intensity) GEMMs, for K x smaller stored activations -- so a large
    effective batch fits in a small SRAM.
    """
    M = layer.M
    mb = M if (microbatch is None or microbatch >= M) else max(1, microbatch)
    n = math.ceil(M / mb)
    sub = Layer(layer.name, M=mb, K=layer.K, N=layer.N)

    f1, fwd_bound = _phase_seconds(mb, layer.N, layer.K, hw, mem)
    b1, bwd_bound, b1_bytes = _backward_seconds(sub, hw, mem, recompute)
    fwd_s, bwd_s = n * f1, n * b1

    # gradient accumulator dW must persist across the n microbatches
    dw = layer.K * layer.N * hw.mac_bytes
    if n > 1 and dw > mem.sram_bytes:
        bwd_s += 2 * (n - 1) * dw / mem.achievable_bw   # spill + reload per chunk

    opt_s = optimizer_seconds(layer, mem, opt, hw)      # once per optimizer step

    # stored activation for this layer's backward: its input X (mb x K).
    # With recomputation it is regenerated, so it is only a *checkpoint*
    # candidate -- sqrt-checkpointing keeps ~1/sqrt(#layers) of them.
    act = float(mb * layer.K * hw.mac_bytes)
    if recompute:
        act *= _CHECKPOINT_FRACTION

    return StepBreakdown(
        layer=layer.name, forward_s=fwd_s, backward_s=bwd_s, optimizer_s=opt_s,
        forward_bound=fwd_bound, backward_bound=bwd_bound,
        backward_bytes=n * b1_bytes, activation_bytes=act,
    )


def model_step(layers, hw: Hardware, mem: Memory,
               opt: Optimizer = ADAM_FP32, *,
               recompute: bool = False, microbatch: int | None = None,
               fused_attention: bool = False):
    """Sum a list of items (GEMM `Layer`s and/or `Attention` blocks) into
    one model training-step estimate. `recompute`/`microbatch` apply to
    `Layer`s only; `fused_attention` applies to `Attention` blocks only
    (each lever ignores items it doesn't apply to)."""
    parts = []
    for item in layers:
        if isinstance(item, Attention):
            parts.append(attention_step(item, hw, mem, fused=fused_attention))
        else:
            parts.append(training_step(item, hw, mem, opt,
                                       recompute=recompute, microbatch=microbatch))
    total = sum(p.total_s for p in parts)
    return total, parts


if __name__ == "__main__":
    from .workloads import GPT2_BLOCK

    hw = Hardware(rows=256, cols=256, clock_hz=1e9)

    fp8 = Optimizer(state_bytes=1, state_resident=True)
    for mb in (2, 8, 32):
        mem = Memory(sram_bytes=mb << 20, dram_bandwidth_bytes_s=100e9)
        print(f"\n-- {mb} MiB SRAM, 256x256 array, 100 GB/s --")
        for label, opt in (
                ("baseline (fp32 streamed Adam)", ADAM_FP32),
                ("+ fp8 resident Adam state", fp8)):
            total, parts = model_step(GPT2_BLOCK, hw, mem, opt)
            fwd = sum(p.forward_s for p in parts) * 1e3
            bwd = sum(p.backward_s for p in parts) * 1e3
            o = sum(p.optimizer_s for p in parts) * 1e3
            print(f"  {label:42s} fwd {fwd:6.2f}  bwd {bwd:6.2f}  "
                  f"opt {o:5.2f}  = {total*1e3:6.2f} ms")
